/* Generated by scripts/write_env_js.py; do not edit on CI */
window.ANALYSIS_API_BASE = "";
window.ANALYSIS_FRONTEND_VERSION = "20260321053646";

/* ===== 股小蜜 API 配置 ===== */
/* 
 * 使用说明：
 * 1. 复制此文件为 env.local.js
 * 2. 填入你的API密钥
 * 3. 将 env.local.js 加入 .gitignore
 * 
 * 或直接在下方填写密钥（仅用于本地开发）
 */

/* Alpha Vantage API 密钥 - 用于获取美股数据
 * 申请地址: https://www.alphavantage.co/support/#api-key
 * 免费额度: 25次/天
 */
window.API_CONFIG = window.API_CONFIG || {};
window.API_CONFIG.ALPHA_VANTAGE_KEY = '';

/* 必应 secret key - 用于港股数据
 * 申请地址: https://rapidapi.com/bingbing/api/bing-stock-search
 */
window.API_CONFIG.BIYING_SECRET_KEY = '';

/* A股股票API密钥 - 用于获取A股数据
 * 推荐使用: https://tushare.pro 或 https://www.akdataapi.com
 */
window.API_CONFIG.CN_STOCK_API_KEY = '';

/* 汇率API密钥（可选）- 使用 Frankfurter 免费API无需密钥
 * 如需更稳定的服务可使用: https://open.er-api.com
 */
window.API_CONFIG.EXCHANGE_RATE_API_KEY = '';

/* API代理地址（可选）- 如需隐藏密钥可配置后端代理
 * 示例: https://your-proxy.com/api
 */
window.API_CONFIG.PROXY_BASE = '';
