#!/usr/bin/env python3
"""Vercel 构建时写入 project-proj_21qCfX0Vycj/env.js（注入 ANALYSIS_API_BASE）。"""
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "project-proj_21qCfX0Vycj" / "env.js"
base = (os.environ.get("ANALYSIS_API_BASE") or "").strip().rstrip("/")

OUT.write_text(
    "/* Generated by scripts/write_env_js.py; do not edit on CI */\n"
    f"window.ANALYSIS_API_BASE = {json.dumps(base)};\n",
    encoding="utf-8",
)
print(f"Wrote {OUT} ANALYSIS_API_BASE={base!r}")
