#!/usr/bin/env python3
"""Vercel 构建时写入 project-proj_21qCfX0Vycj/env.js（注入 ANALYSIS_API_BASE + 前端版本）。"""
import json
import os
import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "project-proj_21qCfX0Vycj" / "env.js"
base = (os.environ.get("ANALYSIS_API_BASE") or "").strip().rstrip("/")

commit = (
    os.environ.get("VERCEL_GIT_COMMIT_SHA")
    or os.environ.get("VERCEL_COMMIT_SHA")
    or ""
).strip()
if commit:
    version = commit[:8]
else:
    version = datetime.datetime.utcnow().strftime("%Y%m%d%H%M%S")

OUT.write_text(
    "/* Generated by scripts/write_env_js.py; do not edit on CI */\n"
    f"window.ANALYSIS_API_BASE = {json.dumps(base)};\n"
    f"window.ANALYSIS_FRONTEND_VERSION = {json.dumps(version)};\n",
    encoding="utf-8",
)
print(
    f"Wrote {OUT} ANALYSIS_API_BASE={base!r} ANALYSIS_FRONTEND_VERSION={version!r}"
)
